version: '3'
services:
  app:
    build: ./docker/php
    volumes:
      - ./app:/var/www/html
    ports:
      - 8081:80
      - 4431:443
      - 3001:3001
    networks:
      app_net:
        ipv4_address: 172.31.0.4
  mariadb:
    build: ./docker/mariadb
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3307:3307
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: 172.31.0.3
  redis:
    image: "redis:latest"
    ports:
      - "6380:6380"
    volumes:
      - "./data/reis:/data"
    networks:
      app_net:
        ipv4_address: 172.31.0.2
volumes:
  dbdata:
networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.31.0.0/24
